<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.bedework.deploy</groupId>
    <artifactId>bw-wfmodules-util-network</artifactId>
    <version>2.2.0-SNAPSHOT</version>
  </parent>

  <modelVersion>4.0.0</modelVersion>

  <artifactId>bw-wfmodules-util-struts2</artifactId>
  <packaging>pom</packaging>
  <name>Bedework wfmodules: util struts2</name>

  <build>
    <plugins>
      <plugin>
        <groupId>org.bedework</groupId>
        <artifactId>bw-util-maven-deploy-wfmodule</artifactId>

        <configuration>
          <moduleName>org.bedework.util.struts2</moduleName>

          <noArtifact>true</noArtifact>

          <jarResources>
            <jarResource>
              <groupId>org.bedework</groupId>
              <artifactId>bw-util-struts2</artifactId>
              <version>${bw-util-network.version}</version>
            </jarResource>
          </jarResources>

          <moduleDependencies>
            <moduleDependency>
              <name>org.bedework.org.apache.struts2.core</name>
            </moduleDependency>
          </moduleDependencies>
        </configuration>
      </plugin>

      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>